config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :tests do
    get 'start', on: :collection
    get 'get_pass', on: :collection
  end

  resources :records

  root "records#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/record.rb
class Record < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
    
    def index
        @records = []
        @records<<Record.where(locker: 1).last()
        @records<<Record.where(locker: 2).last()
        @records<<Record.where(locker: 3).last()

    end

    def show
        @record = Record.find params[:id]
    end

    def new
        @record = Record.new
    end

    def create
        record = Record.new create_params
        record.status = 0
        if record.save
            redirect_to record, notice:'Record creado exitosamente'
        else
            render :new
        end
    end
    
    private

    def create_params
        params.require(:record).permit(:locker,:password_deposit,:password_retire)
    end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

    def show
      number = params[:id]
      number2 = rand(1..100)
      data = { url_number: number.to_s, random_number: number2.to_s }

      respond_to do |format|
        format.json { render json: data }
      end
    end

    def start
      record1 = Record.where(locker: 1).last()
      record2 = Record.where(locker: 2).last()
      record3 = Record.where(locker: 3).last()
      data = {password_deposit1: record1.password_deposit, password_deposit2: record2.password_deposit, password_deposit3: record3.password_deposit, password_retire1: record1.password_retire, password_retire2: record2.password_retire, password_retire3: record3.password_retire}
      respond_to do |format|
        format.json { render json: data }
      end
    end

    def get_pass
      locker = params[:locker].to_i
      pass = params[:password].to_i
      if pass == 0
        password = Record.where(locker: locker).last().password_deposit
      else
        password = Record.where(locker: locker).last().password_retire
      end
      data = {password: password}

      respond_to do |format|
        format.json { render json: data }
      end
    end

    def index
      
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/layouts/_flash.html.erb
<%if notice%>

    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%=notice%>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

<%end%>

<%if alert%>

    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%=alert%>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

<%end%>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light separation">
  <div class="container-fluid">
    <%= link_to 'Records',root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home',root_path, class:"nav-link active"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Crear record',new_record_path, class:"nav-link active"%>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestMicrocontroller</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <style>
      .separation {
        margin-bottom: 12px;
      }
    </style>
  </head>

  <body>
    <%= render partial: 'layouts/navbar' %>
    <div class="container">
      <%= render partial: 'layouts/flash' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/records/_simple_records.html.erb
<div class="card border-dark mb-3 separation">
  <div class="card-header">
    <div class="row">
      <div class="col-6">
          Status: <%= simple_records.status%>
      </div>
      <div class="col-6">
          Locker: <%= simple_records.locker%>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-6">
        <div class="card-body text-dark">
            <h5 class="card-title">Contraseña de depósito</h5>
            <p class="card-text"> <%= simple_records.password_deposit %> </p>
        </div>
    </div>

    <div class="col-6">
        <div class="card-body text-dark">
            <h5 class="card-title">Contraseña de retiro</h5>
            <p class="card-text"> <%= simple_records.password_retire %> </p>
        </div>
    </div>
  </div>
</div>

app/views/records/index.html.erb
<%= render partial: 'simple_records',collection: @records%>

app/views/records/new.html.erb
<h3>Crear registro</h3>

<%=form_with model: @record do |f|%>

    <div class="form-row separation">
        <div class="form-group col-6">
            <%= f.label :password_deposit, "Contraseña depósito" %><br />
            <%= f.text_field :password_deposit,placeholder: 'Número de 6 cifras ej: 038174', class: "form-control"%>
        </div>
    </div>

    <div class="form-row separation">
        <div class="form-group col-6">
            <%= f.label :password_retire, "Contraseña retiro" %><br />
            <%= f.text_field :password_retire,placeholder: 'Número de 6 cifras ej: 038174', class: "form-control"%>
        </div>
    </div>

    <div class="form-group separation">
        <%= f.label :Locker %>
        <%= f.select :locker, options_for_select([1, 2, 3]), class: 'form-control' %>
    </div>

    <%=f.submit 'Guardar', class:'btn btn-primary'%>
<%end%>

app/views/records/show.html.erb
<%= render partial: 'simple_records',locals: { simple_records: @record }%>